# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createRecipe_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1004, 845)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(80, 10, 901, 21))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.provenance = QtWidgets.QLineEdit(Form)
        self.provenance.setGeometry(QtCore.QRect(80, 40, 901, 21))
        self.provenance.setObjectName("provenance")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 72, 15))
        self.label_3.setObjectName("label_3")
        self.cook = QtWidgets.QLineEdit(Form)
        self.cook.setGeometry(QtCore.QRect(80, 130, 901, 21))
        self.cook.setText("")
        self.cook.setObjectName("cook")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 72, 15))
        self.label_4.setObjectName("label_4")
        self.use = QtWidgets.QLineEdit(Form)
        self.use.setGeometry(QtCore.QRect(80, 160, 901, 21))
        self.use.setText("")
        self.use.setObjectName("use")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 400, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 540, 72, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(20, 700, 72, 15))
        self.label_9.setObjectName("label_9")
        self.recipe = QtWidgets.QPlainTextEdit(Form)
        self.recipe.setGeometry(QtCore.QRect(80, 70, 901, 51))
        self.recipe.setObjectName("recipe")
        self.symptom = QtWidgets.QPlainTextEdit(Form)
        self.symptom.setGeometry(QtCore.QRect(80, 190, 901, 141))
        self.symptom.setObjectName("symptom")
        self.reason = QtWidgets.QPlainTextEdit(Form)
        self.reason.setGeometry(QtCore.QRect(80, 340, 901, 141))
        self.reason.setObjectName("reason")
        self.ban = QtWidgets.QPlainTextEdit(Form)
        self.ban.setGeometry(QtCore.QRect(80, 490, 901, 141))
        self.ban.setObjectName("ban")
        self.alter = QtWidgets.QPlainTextEdit(Form)
        self.alter.setGeometry(QtCore.QRect(80, 640, 901, 141))
        self.alter.setObjectName("alter")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(890, 800, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.BJ = QtWidgets.QPushButton(Form)
        self.BJ.setGeometry(QtCore.QRect(780, 800, 93, 28))
        self.BJ.setObjectName("BJ")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "方名"))
        self.label_2.setText(_translate("Form", "来源"))
        self.label_3.setText(_translate("Form", "处方"))
        self.label_4.setText(_translate("Form", "制法"))
        self.label_5.setText(_translate("Form", "功用"))
        self.label_6.setText(_translate("Form", "主治"))
        self.label_7.setText(_translate("Form", "方解"))
        self.label_8.setText(_translate("Form", "禁忌"))
        self.label_9.setText(_translate("Form", "增减"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.BJ.setText(_translate("Form", "跳过"))
