# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 565)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 251, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 249, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.LMed = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.LMed.setGeometry(QtCore.QRect(10, 10, 231, 481))
        self.LMed.setObjectName("LMed")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.IFind = QtWidgets.QLineEdit(Form)
        self.IFind.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.IFind.setObjectName("IFind")
        self.BFind = QtWidgets.QPushButton(Form)
        self.BFind.setGeometry(QtCore.QRect(170, 10, 93, 28))
        self.BFind.setObjectName("BFind")
        self.BAdd = QtWidgets.QPushButton(Form)
        self.BAdd.setGeometry(QtCore.QRect(270, 100, 93, 28))
        self.BAdd.setObjectName("BAdd")
        self.BDelete = QtWidgets.QPushButton(Form)
        self.BDelete.setGeometry(QtCore.QRect(270, 150, 93, 28))
        self.BDelete.setObjectName("BDelete")
        self.BClear = QtWidgets.QPushButton(Form)
        self.BClear.setGeometry(QtCore.QRect(270, 200, 93, 28))
        self.BClear.setObjectName("BClear")
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        self.scrollArea_2.setGeometry(QtCore.QRect(370, 50, 251, 501))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 249, 499))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.LSelected = QtWidgets.QListView(self.scrollAreaWidgetContents_2)
        self.LSelected.setGeometry(QtCore.QRect(10, 10, 231, 481))
        self.LSelected.setObjectName("LSelected")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.BRun = QtWidgets.QPushButton(Form)
        self.BRun.setGeometry(QtCore.QRect(270, 250, 93, 28))
        self.BRun.setObjectName("BRun")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 20, 101, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "基本配伍及禁忌知识模糊查询"))
        self.BFind.setText(_translate("Form", "查找"))
        self.BAdd.setText(_translate("Form", ">>"))
        self.BDelete.setText(_translate("Form", "<<"))
        self.BClear.setText(_translate("Form", "清空"))
        self.BRun.setText(_translate("Form", "查询"))
        self.label.setText(_translate("Form", "已选择药材"))
