# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'herb_input_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(722, 510)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setToolTipDuration(-1)
        self.label.setObjectName("label")
        self.IName = QtWidgets.QLineEdit(Dialog)
        self.IName.setGeometry(QtCore.QRect(70, 20, 631, 21))
        self.IName.setToolTipDuration(-1)
        self.IName.setObjectName("IName")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 72, 15))
        self.label_2.setToolTipDuration(-1)
        self.label_2.setObjectName("label_2")
        self.IIntro = QtWidgets.QPlainTextEdit(Dialog)
        self.IIntro.setGeometry(QtCore.QRect(70, 60, 631, 101))
        self.IIntro.setToolTipDuration(-1)
        self.IIntro.setObjectName("IIntro")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 72, 15))
        self.label_3.setToolTipDuration(-1)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(70, 180, 631, 231))
        self.scrollArea.setToolTipDuration(-1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 629, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.LCom = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.LCom.setGeometry(QtCore.QRect(10, 10, 611, 211))
        self.LCom.setToolTipDuration(-1)
        self.LCom.setObjectName("LCom")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BAdd = QtWidgets.QPushButton(Dialog)
        self.BAdd.setGeometry(QtCore.QRect(210, 420, 93, 28))
        self.BAdd.setToolTipDuration(-1)
        self.BAdd.setObjectName("BAdd")
        self.BDelete = QtWidgets.QPushButton(Dialog)
        self.BDelete.setGeometry(QtCore.QRect(340, 420, 93, 28))
        self.BDelete.setToolTipDuration(-1)
        self.BDelete.setObjectName("BDelete")
        self.BN = QtWidgets.QPushButton(Dialog)
        self.BN.setGeometry(QtCore.QRect(600, 470, 93, 28))
        self.BN.setToolTipDuration(-1)
        self.BN.setObjectName("BN")
        self.BY = QtWidgets.QPushButton(Dialog)
        self.BY.setGeometry(QtCore.QRect(470, 470, 93, 28))
        self.BY.setToolTipDuration(-1)
        self.BY.setObjectName("BY")
        self.ICom = QtWidgets.QLineEdit(Dialog)
        self.ICom.setGeometry(QtCore.QRect(70, 420, 131, 31))
        self.ICom.setToolTipDuration(-1)
        self.ICom.setObjectName("ICom")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "药材输入"))
        self.label.setText(_translate("Dialog", "名称"))
        self.label_2.setText(_translate("Dialog", "介绍"))
        self.label_3.setText(_translate("Dialog", "组成"))
        self.BAdd.setText(_translate("Dialog", "添加组分"))
        self.BDelete.setText(_translate("Dialog", "删除组分"))
        self.BN.setText(_translate("Dialog", "取消"))
        self.BY.setText(_translate("Dialog", "确定"))
