# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learn_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1101, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{background-color:#303030;}\n"
"")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 90, 351, 611))
        self.scrollArea.setStyleSheet("border-width:1px;\n"
"border-radius:10px;\n"
"background-color:#E0E0E0;\n"
"outline:0px;\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 611))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.learnlist = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.learnlist.setGeometry(QtCore.QRect(10, 10, 331, 591))
        self.learnlist.setStyleSheet("QListView{\n"
"    border:none;\n"
"    background-color:#E0E0E0;\n"
"}\n"
"QListView::item{\n"
"    border-radius:5px;\n"
"    background-color:white;\n"
"    color:black;\n"
"    margin:10px;\n"
"    padding:5px;\n"
"    font-size:12px;\n"
"}\n"
"QListView::item:selected{\n"
"    border-radius:5px;\n"
"    background-color:black;\n"
"    color:white;\n"
"    margin:10px;\n"
"    padding:5px;\n"
"    font-size:12px;\n"
"}")
        self.learnlist.setObjectName("learnlist")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BFind = QtWidgets.QPushButton(Form)
        self.BFind.setGeometry(QtCore.QRect(270, 50, 93, 28))
        self.BFind.setObjectName("BFind")
        self.IFind = QtWidgets.QLineEdit(Form)
        self.IFind.setGeometry(QtCore.QRect(20, 50, 241, 31))
        self.IFind.setStyleSheet("border-radius:10px;")
        self.IFind.setObjectName("IFind")
        self.content = QtWidgets.QScrollArea(Form)
        self.content.setGeometry(QtCore.QRect(380, 50, 711, 651))
        self.content.setWidgetResizable(True)
        self.content.setObjectName("content")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 709, 649))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.GPlays = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.GPlays.setGeometry(QtCore.QRect(10, 609, 691, 31))
        self.GPlays.setTitle("")
        self.GPlays.setObjectName("GPlays")
        self.SProgess = QtWidgets.QSlider(self.GPlays)
        self.SProgess.setGeometry(QtCore.QRect(40, 0, 351, 22))
        self.SProgess.setMaximum(100)
        self.SProgess.setOrientation(QtCore.Qt.Horizontal)
        self.SProgess.setObjectName("SProgess")
        self.BPlay = QtWidgets.QPushButton(self.GPlays)
        self.BPlay.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.BPlay.setObjectName("BPlay")
        self.SVolume = QtWidgets.QSlider(self.GPlays)
        self.SVolume.setGeometry(QtCore.QRect(580, 0, 101, 22))
        self.SVolume.setMaximum(100)
        self.SVolume.setProperty("value", 50)
        self.SVolume.setOrientation(QtCore.Qt.Horizontal)
        self.SVolume.setObjectName("SVolume")
        self.label = QtWidgets.QLabel(self.GPlays)
        self.label.setGeometry(QtCore.QRect(540, -6, 72, 31))
        self.label.setObjectName("label")
        self.TAll = QtWidgets.QLabel(self.GPlays)
        self.TAll.setGeometry(QtCore.QRect(491, -11, 41, 41))
        self.TAll.setObjectName("TAll")
        self.TNow = QtWidgets.QLabel(self.GPlays)
        self.TNow.setGeometry(QtCore.QRect(430, -10, 41, 41))
        self.TNow.setObjectName("TNow")
        self.label_4 = QtWidgets.QLabel(self.GPlays)
        self.label_4.setGeometry(QtCore.QRect(470, -10, 21, 41))
        self.label_4.setObjectName("label_4")
        self.content.setWidget(self.scrollAreaWidgetContents_2)
        self.welcome = QtWidgets.QLabel(Form)
        self.welcome.setGeometry(QtCore.QRect(20, 10, 961, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("color:white")
        self.welcome.setObjectName("welcome")
        self.BLog = QtWidgets.QPushButton(Form)
        self.BLog.setGeometry(QtCore.QRect(990, 10, 93, 28))
        self.BLog.setObjectName("BLog")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "知识学习"))
        self.BFind.setText(_translate("Form", "查找"))
        self.BPlay.setText(_translate("Form", ">"))
        self.label.setText(_translate("Form", "音量"))
        self.TAll.setText(_translate("Form", "11:20"))
        self.TNow.setText(_translate("Form", "11:20"))
        self.label_4.setText(_translate("Form", " /"))
        self.welcome.setText(_translate("Form", "TextLabel"))
        self.BLog.setText(_translate("Form", "学习记录"))
