# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(883, 473)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 301, 111))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:black;\n"
"background-color:#BBBBBBBB")
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(370, 50, 641, 371))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color:#004400;\n"
"    border-radius:50px;\n"
"    border-width:5px;\n"
"    border-style:soild;\n"
"    border-color:#ffffff;\n"
"}\n"
"QPushButton{\n"
"    background-color:#F6F6F6;\n"
"    border-radius:5px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.BLogin = QtWidgets.QPushButton(self.groupBox)
        self.BLogin.setGeometry(QtCore.QRect(350, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BLogin.setFont(font)
        self.BLogin.setObjectName("BLogin")
        self.IName = QtWidgets.QLineEdit(self.groupBox)
        self.IName.setGeometry(QtCore.QRect(200, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IName.setFont(font)
        self.IName.setText("")
        self.IName.setObjectName("IName")
        self.BRegis = QtWidgets.QPushButton(self.groupBox)
        self.BRegis.setGeometry(QtCore.QRect(130, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BRegis.setFont(font)
        self.BRegis.setObjectName("BRegis")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(100, 100, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.IPassword = QtWidgets.QLineEdit(self.groupBox)
        self.IPassword.setGeometry(QtCore.QRect(200, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IPassword.setFont(font)
        self.IPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.IPassword.setObjectName("IPassword")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.tip = QtWidgets.QLabel(self.groupBox)
        self.tip.setGeometry(QtCore.QRect(100, 320, 391, 16))
        self.tip.setStyleSheet("color:white")
        self.tip.setText("")
        self.tip.setObjectName("tip")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 301, 111))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:black;\n"
"background-color:#BBBBBBBB\n"
"")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录到学习系统"))
        self.label_3.setText(_translate("Form", "中医知识"))
        self.BLogin.setText(_translate("Form", "登录"))
        self.BRegis.setText(_translate("Form", "注册"))
        self.label.setText(_translate("Form", "用户名"))
        self.label_2.setText(_translate("Form", "密码"))
        self.label_4.setText(_translate("Form", "学习系统"))
