# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'med_db_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(928, 766)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 220, 891, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 889, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.TRecipe = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.TRecipe.setGeometry(QtCore.QRect(10, 10, 871, 451))
        self.TRecipe.setObjectName("TRecipe")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BY = QtWidgets.QPushButton(Form)
        self.BY.setGeometry(QtCore.QRect(680, 710, 93, 28))
        self.BY.setObjectName("BY")
        self.BN = QtWidgets.QPushButton(Form)
        self.BN.setGeometry(QtCore.QRect(810, 710, 93, 28))
        self.BN.setObjectName("BN")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 891, 192))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.IFind = QtWidgets.QPlainTextEdit(self.splitter)
        self.IFind.setObjectName("IFind")
        self.BFind = QtWidgets.QPushButton(self.splitter)
        self.BFind.setObjectName("BFind")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "辅助开药"))
        self.BY.setText(_translate("Form", "确定"))
        self.BN.setText(_translate("Form", "取消"))
        self.label.setText(_translate("Form", "症状"))
        self.BFind.setText(_translate("Form", "查找"))
