# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'med_normal_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(997, 682)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 981, 151))
        self.groupBox.setObjectName("groupBox")
        self.ISick = QtWidgets.QTextEdit(self.groupBox)
        self.ISick.setGeometry(QtCore.QRect(10, 20, 961, 121))
        self.ISick.setObjectName("ISick")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 981, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 961, 221))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.TContent = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.TContent.setGeometry(QtCore.QRect(0, 0, 961, 221))
        self.TContent.setObjectName("TContent")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 250, 31, 16))
        self.label.setObjectName("label")
        self.IMed = QtWidgets.QLineEdit(self.groupBox_2)
        self.IMed.setGeometry(QtCore.QRect(50, 250, 113, 21))
        self.IMed.setObjectName("IMed")
        self.ICount = QtWidgets.QLineEdit(self.groupBox_2)
        self.ICount.setGeometry(QtCore.QRect(470, 250, 113, 21))
        self.ICount.setText("")
        self.ICount.setObjectName("ICount")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(400, 250, 61, 16))
        self.label_2.setObjectName("label_2")
        self.BAdd = QtWidgets.QPushButton(self.groupBox_2)
        self.BAdd.setGeometry(QtCore.QRect(680, 250, 93, 28))
        self.BAdd.setObjectName("BAdd")
        self.BClear = QtWidgets.QPushButton(self.groupBox_2)
        self.BClear.setGeometry(QtCore.QRect(880, 250, 93, 28))
        self.BClear.setObjectName("BClear")
        self.BDelete = QtWidgets.QPushButton(self.groupBox_2)
        self.BDelete.setGeometry(QtCore.QRect(780, 250, 93, 28))
        self.BDelete.setObjectName("BDelete")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(190, 250, 61, 16))
        self.label_3.setObjectName("label_3")
        self.IDeal = QtWidgets.QLineEdit(self.groupBox_2)
        self.IDeal.setGeometry(QtCore.QRect(260, 250, 113, 21))
        self.IDeal.setObjectName("IDeal")
        self.BConfirm = QtWidgets.QPushButton(Form)
        self.BConfirm.setGeometry(QtCore.QRect(450, 640, 93, 28))
        self.BConfirm.setObjectName("BConfirm")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 470, 981, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.IAdeal = QtWidgets.QTextEdit(self.groupBox_3)
        self.IAdeal.setGeometry(QtCore.QRect(10, 20, 961, 31))
        self.IAdeal.setObjectName("IAdeal")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 540, 981, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.IUse = QtWidgets.QTextEdit(self.groupBox_4)
        self.IUse.setGeometry(QtCore.QRect(10, 20, 961, 31))
        self.IUse.setObjectName("IUse")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 610, 72, 15))
        self.label_4.setObjectName("label_4")
        self.IAcount = QtWidgets.QLineEdit(Form)
        self.IAcount.setGeometry(QtCore.QRect(60, 610, 113, 21))
        self.IAcount.setObjectName("IAcount")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "开药"))
        self.groupBox.setTitle(_translate("Form", "症状"))
        self.groupBox_2.setTitle(_translate("Form", "药方"))
        self.label.setText(_translate("Form", "药材"))
        self.label_2.setText(_translate("Form", "剂量(克）"))
        self.BAdd.setText(_translate("Form", "添加"))
        self.BClear.setText(_translate("Form", "清空"))
        self.BDelete.setText(_translate("Form", "删除"))
        self.label_3.setText(_translate("Form", "预处理"))
        self.IDeal.setText(_translate("Form", "无"))
        self.BConfirm.setText(_translate("Form", "开药"))
        self.groupBox_3.setTitle(_translate("Form", "制法"))
        self.IAdeal.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">磨成细粉末</p></body></html>"))
        self.groupBox_4.setTitle(_translate("Form", "用法"))
        self.IUse.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">每天一剂，加水煎服</p></body></html>"))
        self.label_4.setText(_translate("Form", "剂数"))
        self.IAcount.setText(_translate("Form", "1"))
