# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'med_data_user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(911, 599)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(18, 60, 871, 471))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Tcontent = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.Tcontent.setGeometry(QtCore.QRect(10, 10, 851, 451))
        self.Tcontent.setObjectName("Tcontent")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(620, 20, 264, 28))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.IFind = QtWidgets.QLineEdit(self.splitter)
        self.IFind.setObjectName("IFind")
        self.BFind = QtWidgets.QPushButton(self.splitter)
        self.BFind.setObjectName("BFind")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(18, 20, 231, 21))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.CType = QtWidgets.QComboBox(self.splitter_2)
        self.CType.setObjectName("CType")
        self.CType.addItem("")
        self.CType.addItem("")
        self.CType.addItem("")
        self.BAdvanced = QtWidgets.QPushButton(Form)
        self.BAdvanced.setEnabled(True)
        self.BAdvanced.setGeometry(QtCore.QRect(782, 550, 111, 28))
        self.BAdvanced.setObjectName("BAdvanced")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setGeometry(QtCore.QRect(30, 550, 279, 28))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.BAdd = QtWidgets.QPushButton(self.splitter_3)
        self.BAdd.setObjectName("BAdd")
        self.BDelete = QtWidgets.QPushButton(self.splitter_3)
        self.BDelete.setObjectName("BDelete")
        self.BChange = QtWidgets.QPushButton(self.splitter_3)
        self.BChange.setObjectName("BChange")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中药数据库"))
        self.BFind.setText(_translate("Form", "查找"))
        self.label.setText(_translate("Form", "类型"))
        self.CType.setItemText(0, _translate("Form", "药材"))
        self.CType.setItemText(1, _translate("Form", "配伍关系"))
        self.CType.setItemText(2, _translate("Form", "药方"))
        self.BAdvanced.setText(_translate("Form", "高级配伍查找"))
        self.BAdd.setText(_translate("Form", "添加"))
        self.BDelete.setText(_translate("Form", "删除"))
        self.BChange.setText(_translate("Form", "更改"))
