# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relation_input_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 155)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.BY = QtWidgets.QPushButton(Form)
        self.BY.setGeometry(QtCore.QRect(390, 110, 93, 28))
        self.BY.setObjectName("BY")
        self.BN = QtWidgets.QPushButton(Form)
        self.BN.setGeometry(QtCore.QRect(520, 110, 93, 28))
        self.BN.setObjectName("BN")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 19, 30, 16))
        self.label_3.setObjectName("label_3")
        self.IMed1 = QtWidgets.QLineEdit(Form)
        self.IMed1.setGeometry(QtCore.QRect(20, 41, 171, 31))
        self.IMed1.setObjectName("IMed1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 38, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(380, 19, 38, 15))
        self.label_5.setObjectName("label_5")
        self.IMed2 = QtWidgets.QLineEdit(Form)
        self.IMed2.setGeometry(QtCore.QRect(380, 40, 171, 31))
        self.IMed2.setObjectName("IMed2")
        self.CRelation = QtWidgets.QComboBox(Form)
        self.CRelation.setGeometry(QtCore.QRect(240, 40, 91, 31))
        self.CRelation.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CRelation.setObjectName("CRelation")
        self.CRelation.addItem("")
        self.CRelation.addItem("")
        self.CRelation.addItem("")
        self.CRelation.addItem("")
        self.CRelation.addItem("")
        self.CRelation.addItem("")
        self.CRelation.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "配伍输入"))
        self.BY.setText(_translate("Form", "确定"))
        self.BN.setText(_translate("Form", "取消"))
        self.label_3.setText(_translate("Form", "关系"))
        self.label_4.setText(_translate("Form", "药材1"))
        self.label_5.setText(_translate("Form", "药材2"))
        self.CRelation.setItemText(0, _translate("Form", "单行"))
        self.CRelation.setItemText(1, _translate("Form", "须"))
        self.CRelation.setItemText(2, _translate("Form", "使"))
        self.CRelation.setItemText(3, _translate("Form", "畏"))
        self.CRelation.setItemText(4, _translate("Form", "恶"))
        self.CRelation.setItemText(5, _translate("Form", "反"))
        self.CRelation.setItemText(6, _translate("Form", "杀"))
