# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(729, 652)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/med.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{\n"
"    background-image:url(\"./icon/first_background.png\")\n"
"}\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius:20px;\n"
"    background-color:white;\n"
"    font-weight:bold\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius:20px;\n"
"    background-color:#DFDFDF;\n"
"    font-weight:bold\n"
"}\n"
"")
        self.BLearn = QtWidgets.QPushButton(Form)
        self.BLearn.setGeometry(QtCore.QRect(130, 70, 451, 121))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BLearn.setFont(font)
        self.BLearn.setIconSize(QtCore.QSize(20, 20))
        self.BLearn.setObjectName("BLearn")
        self.BFind = QtWidgets.QPushButton(Form)
        self.BFind.setGeometry(QtCore.QRect(130, 240, 451, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BFind.setFont(font)
        self.BFind.setObjectName("BFind")
        self.BDecide = QtWidgets.QPushButton(Form)
        self.BDecide.setGeometry(QtCore.QRect(130, 420, 451, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BDecide.setFont(font)
        self.BDecide.setObjectName("BDecide")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中药配伍决策辅助系统"))
        self.BLearn.setText(_translate("Form", "基础知识学习"))
        self.BFind.setText(_translate("Form", "中药数据库操作"))
        self.BDecide.setText(_translate("Form", "对症辅助决策下方"))
